from __future__ import annotations

from pathlib import Path
import json
import math
from typing import Any
from note_model import Note, note_name

EPS = 1e-9


def new_level() -> dict[str, Any]:
    return {
        "settings": {
            "version": 15,
            "artist": "AdopyHzEditor",
            "song": "Hz Chart",
            "author": "AdopyHzEditor",
            "separateCountdownTime": "Enabled",
            "previewImage": "",
            "previewIcon": "",
            "previewIconColor": "003f52",
            "previewSongStart": 0,
            "previewSongDuration": 10,
            "seizureWarning": "Disabled",
            "levelDesc": "Generated by AdopyHzEditor",
            "levelTags": "Hz Chart",
            "artistLinks": "",
            "speedTrialAim": 0,
            "difficulty": 1,
            "requiredMods": [],
        },
        # floor 0 is a clean starter tile. Hz generation starts at floor 1.
        "angleData": [0, 0],
        "actions": [],
        "decorations": [],
    }


def clean_angle(x: float) -> int | float:
    x %= 360.0
    if abs(x - round(x)) < 1e-9:
        return int(round(x)) % 360
    return round(x, 9)


def clean_relative_angle(x: float) -> float:
    """
    Relative angle for generated ADOFAI tiles.
    Avoid exact 0 because it can create awkward/ambiguous U-turn-like geometry.
    """
    v = float(x) % 360.0
    if abs(v) < 1e-9:
        v = 360.0
    return round(v, 9)


def nearest_cardinal_angle(abs_angle: float, step: float = 90.0) -> float:
    step = max(1e-6, float(step))
    return clean_angle(round(float(abs_angle) / step) * step)


def final_visual_angle(
    *,
    mode: str,
    prev_abs: float,
    scaled_final_angle: float,
    custom_final_angle: float,
    cardinal_step: float = 90.0,
) -> float:
    """
    Choose the visual final-tile relative angle.

    scaled:
        current mathematically scaled fractional angle.
    straight:
        legacy alias for custom 180. Not exposed in the UI.
    cardinal:
        choose a relative angle that makes the final absolute tile direction snap
        to the nearest cardinal/grid direction.
    custom:
        use user-specified relative angle.
    """
    mode = (mode or "scaled").lower().replace(" ", "_").replace("-", "_")

    if mode in ("straight", "straight_relative"):
        return 180.0

    if mode in ("custom", "custom_relative"):
        return clean_relative_angle(custom_final_angle)

    if mode in ("cardinal", "snap_cardinal", "snap_to_cardinal"):
        scaled_abs = clean_angle(prev_abs + 180.0 - scaled_final_angle)
        desired_abs = nearest_cardinal_angle(scaled_abs, cardinal_step)
        return clean_relative_angle(prev_abs + 180.0 - desired_abs)

    return float(scaled_final_angle)


def add_relative(angle_data: list[Any], rel: float) -> None:
    prev = float(angle_data[-1])
    cur = prev + 180.0 - float(rel)
    angle_data.append(clean_angle(cur))


def speed_event_floor(floor: int) -> int:
    """
    ADOFAI editor visually shows the speed event on the corner/transition tile
    when placed at the generation floor.

    The requested placement is the next Hz section tile, so speed events are
    written one floor later. floor 0 still stays clean.
    """
    return max(1, int(floor) + 1)


def set_bpm(floor: int, bpm: float) -> dict[str, Any]:
    return {
        "floor": speed_event_floor(floor),
        "eventType": "SetSpeed",
        "speedType": "Bpm",
        "beatsPerMinute": round(float(bpm), 6),
        "bpmMultiplier": 1,
    }


def pause_beats(floor: int, beats: float) -> dict[str, Any]:
    return {
        "floor": int(floor),
        "eventType": "Pause",
        "duration": round(max(0.0, float(beats)), 6),
        "countdownTicks": 0,
        "angleCorrectionDir": -1,
    }


def track_color_for_visual(track_visual: str) -> tuple[str, str]:
    """
    Return (trackColor, secondaryTrackColor).
    Alpha is the last byte: RRGGBBAA.
    """
    mode = (track_visual or "normal").lower()

    if mode == "hidden":
        return "debb7b00", "ffffff00"
    if mode == "very faint":
        return "debb7b18", "ffffff10"
    if mode == "faint":
        return "debb7b40", "ffffff22"

    return "debb7bff", "ffffffff"


def color_track_event(floor: int, track_visual: str) -> dict[str, Any]:
    track, secondary = track_color_for_visual(track_visual)
    return {
        "floor": int(floor),
        "eventType": "ColorTrack",
        "trackColorType": "Single",
        "trackColor": track,
        "secondaryTrackColor": secondary,
        "trackColorAnimDuration": 0,
        "trackColorPulse": "None",
        "trackPulseLength": 10,
        "trackStyle": "Standard",
        "trackTexture": "",
        "trackTextureScale": 1,
        "trackAnimation": "None",
        "beatsAhead": 3,
        "trackDisappearanceAnimation": "None",
        "beatsBehind": 4,
    }


def apply_track_visual(level: dict[str, Any], actions: list[dict[str, Any]], track_visual: str) -> None:
    mode = (track_visual or "normal").lower()
    track, secondary = track_color_for_visual(mode)

    settings = level.setdefault("settings", {})
    settings["trackColorType"] = "Single"
    settings["trackColor"] = track
    settings["secondaryTrackColor"] = secondary
    settings["trackColorAnimDuration"] = 0
    settings["trackColorPulse"] = "None"
    settings["trackPulseLength"] = 10
    settings["trackStyle"] = "Standard"

    if mode != "normal":
        actions.append(color_track_event(0, mode))


def pause_seconds(actions: list[dict[str, Any]], floor: int, seconds: float, current_bpm: float | None) -> None:
    if seconds <= 1e-6:
        return
    bpm = max(1e-6, float(current_bpm or 120.0))
    actions.append(pause_beats(floor, seconds * bpm / 60.0))


def keycount_floor_x(keycount: float) -> int:
    return max(1, int(math.floor(max(0.0, keycount) + EPS)))


def choose_change_x(keycount: float, mode: str, fixed: float) -> float:
    x_floor = keycount_floor_x(keycount)
    mode = (mode or "floor").lower().replace(" ", "_").replace("-", "_")

    if mode == "fixed":
        return max(0.000001, float(fixed))
    if mode in ("lowest_floor", "lowest", "min_floor", "minimum_floor"):
        return max(1.0, float(fixed))
    if mode == "round":
        return max(1.0, float(round(keycount)))
    if mode == "ceil":
        return max(1.0, float(math.ceil(keycount)))

    return max(1.0, float(x_floor))


def build_adofai_debug_rows(
    notes: list[Note],
    *,
    method: str = "rabbit_zip",
    base_bpm: float = 175.0,
    angle_only_bpm: float = 1600.0,
    rabbit_x_mode: str = "floor",
    rabbit_fixed_x: float = 8.0,
    max_tiles: int = 200000,
    max_tiles_per_note: int = 5000,
    curve_step_sec: float = 0.025,
    curve_pitch_step: float = 0.25,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
    **_: Any,
) -> list[dict[str, Any]]:
    """
    Build a per-note / per-zip calculation preview for ADOFAI Hz export.

    This does not write a file. It mirrors the export calculations enough to
    make angle/BPM/keycount issues visible before exporting.
    """
    flattened_notes = flatten_curve_notes(notes, curve_step_sec=curve_step_sec, curve_pitch_step=curve_pitch_step)
    sorted_notes, first_note_offset = normalize_notes_to_first(flattened_notes)

    method_key = (method or "rabbit_zip").lower().replace(" ", "_").replace("-", "_")
    play_bpm = max(1e-6, float(angle_only_bpm if method_key == "angle_only" else base_bpm))

    global_lowest_floor_x = compute_lowest_floor_x(sorted_notes)
    effective_fixed_x = global_lowest_floor_x if (rabbit_x_mode or "").lower().replace(" ", "_").replace("-", "_") in (
        "lowest_floor", "lowest", "min_floor", "minimum_floor"
    ) else rabbit_fixed_x

    rows: list[dict[str, Any]] = []
    floor = 1
    now = 0.0
    tiles_so_far = 0
    prev_abs = 0.0

    for idx, n in enumerate(sorted_notes):
        if max_tiles > 0 and tiles_so_far >= max_tiles:
            break

        freq = float(n.freq)
        dur = float(n.duration)
        if freq <= 0 or dur <= 0:
            continue

        pause_seconds_before = max(0.0, n.start - now)
        overlap = n.start < now - 1e-6

        limit = max_tiles_per_note
        if max_tiles > 0:
            remain = max_tiles - tiles_so_far
            limit = min(limit, remain) if limit > 0 else remain

        row: dict[str, Any] = {
            "index": idx,
            "floor_start": floor,
            "start_s": round(n.start, 6),
            "end_s": round(n.end, 6),
            "duration_s": round(dur, 6),
            "pause_before_s": round(pause_seconds_before, 6),
            "overlap": bool(overlap),
            "kind": n.kind,
            "note": note_name(n.midi),
            "midi": round(float(n.midi), 6),
            "freq_hz": round(freq, 6),
            "method": method_key,
            "target_angle": "" if n.target_angle is None else round(float(n.target_angle), 6),
            "target_angle_used": False,
            "target_angle_ignored": bool(method_key == "angle_only" and n.target_angle is not None),
            "warning": "",
        }

        emitted = 0
        final_visual_used = False
        final_bpm = ""
        effective_bpm = ""

        if method_key == "direct_180":
            bpm = freq * 60.0
            keycount = freq * dur
            whole = int(math.floor(keycount + EPS))
            frac = keycount - whole
            emitted = whole
            if limit > 0:
                emitted = min(emitted, limit)

            final_angle = 180.0 if frac > 1e-6 and (limit <= 0 or emitted < limit) else ""
            final_bpm = (bpm / frac) if isinstance(final_angle, float) and frac > 1e-6 else ""
            if isinstance(final_angle, float):
                emitted += 1

            row.update({
                "keycount": round(keycount, 6),
                "whole": whole,
                "frac": round(frac, 6),
                "change_x": "",
                "angle": 180.0,
                "auto_angle": 180.0,
                "final_angle_scaled": "" if frac <= 1e-6 else round(180.0 * frac, 6),
                "final_angle_effective": final_angle if final_angle == "" else round(final_angle, 6),
                "effective_bpm": round(bpm, 6),
                "final_bpm": "" if final_bpm == "" else round(float(final_bpm), 6),
                "tiles_est": emitted,
                "final_visual_used": False,
                "lowest_floor_x": global_lowest_floor_x,
                "effective_fixed_x": round(float(effective_fixed_x), 6),
            })

        elif method_key == "angle_only":
            keycount = freq * dur
            whole = int(math.floor(keycount + EPS))
            frac = keycount - math.floor(keycount)
            angle = clean_relative_angle(play_bpm * 180.0 / max(EPS, freq * 60.0))

            emitted = whole
            if limit > 0:
                emitted = min(emitted, limit)

            scaled_final = angle * frac if frac > 1e-6 else ""
            effective_final = ""
            if frac > 1e-6 and (limit <= 0 or emitted < limit):
                effective_final = final_visual_angle(
                    mode=final_angle_mode,
                    prev_abs=prev_abs,
                    scaled_final_angle=angle * frac,
                    custom_final_angle=final_custom_angle,
                    cardinal_step=final_cardinal_step,
                )
                final_bpm = (freq * 60.0) * (effective_final / max(EPS, 180.0 * frac))
                final_visual_used = abs(float(effective_final) - float(angle * frac)) > 1e-6 or abs(final_bpm - play_bpm) > 1e-6
                emitted += 1

            row.update({
                "keycount": round(keycount, 6),
                "whole": whole,
                "frac": round(frac, 6),
                "change_x": "",
                "angle": round(angle, 6),
                "auto_angle": round(angle, 6),
                "final_angle_scaled": "" if scaled_final == "" else round(float(scaled_final), 6),
                "final_angle_effective": "" if effective_final == "" else round(float(effective_final), 6),
                "effective_bpm": round(play_bpm, 6),
                "final_bpm": "" if final_bpm == "" else round(float(final_bpm), 6),
                "tiles_est": emitted,
                "final_visual_used": bool(final_visual_used),
                "lowest_floor_x": global_lowest_floor_x,
                "effective_fixed_x": round(float(effective_fixed_x), 6),
            })

        else:
            beat_count = dur * play_bpm / 60.0
            keycount = freq * 60.0 * beat_count / max(play_bpm, EPS)
            whole = int(math.floor(keycount + EPS))
            frac = keycount - math.floor(keycount)

            change_x = choose_change_x(keycount, rabbit_x_mode, effective_fixed_x)
            auto_angle = 180.0 * change_x / keycount if keycount > EPS else 180.0

            target_used = n.target_angle is not None and float(n.target_angle) > 0
            angle = float(n.target_angle) if target_used else auto_angle
            bpm = (freq * 60.0) * (angle / 180.0)

            emitted = whole
            if limit > 0:
                emitted = min(emitted, limit)

            scaled_final = angle * frac if frac > 1e-6 else ""
            effective_final = ""
            if frac > 1e-6 and (limit <= 0 or emitted < limit):
                effective_final = final_visual_angle(
                    mode=final_angle_mode,
                    prev_abs=prev_abs,
                    scaled_final_angle=angle * frac,
                    custom_final_angle=final_custom_angle,
                    cardinal_step=final_cardinal_step,
                )
                final_bpm = (freq * 60.0) * (effective_final / max(EPS, 180.0 * frac))
                final_visual_used = abs(float(effective_final) - float(angle * frac)) > 1e-6 or abs(final_bpm - bpm) > 1e-6
                emitted += 1

            row.update({
                "keycount": round(keycount, 6),
                "whole": whole,
                "frac": round(frac, 6),
                "change_x": round(float(change_x), 6),
                "angle": round(angle, 6),
                "auto_angle": round(auto_angle, 6),
                "final_angle_scaled": "" if scaled_final == "" else round(float(scaled_final), 6),
                "final_angle_effective": "" if effective_final == "" else round(float(effective_final), 6),
                "effective_bpm": round(bpm, 6),
                "final_bpm": "" if final_bpm == "" else round(float(final_bpm), 6),
                "tiles_est": emitted,
                "target_angle_used": bool(target_used),
                "final_visual_used": bool(final_visual_used),
                "lowest_floor_x": global_lowest_floor_x,
                "effective_fixed_x": round(float(effective_fixed_x), 6),
            })

        if limit > 0 and row.get("whole", 0) > limit:
            row["warning"] = f"clipped by max_tiles_per_note={limit}"
        if row.get("angle") != "" and isinstance(row.get("angle"), (int, float)) and float(row["angle"]) < 1.0:
            row["warning"] = (row["warning"] + "; " if row["warning"] else "") + "very small angle"

        rows.append(row)

        # Approximate floor/abs angle progression for next debug row.
        floor += int(row.get("tiles_est", 0))
        tiles_so_far += int(row.get("tiles_est", 0))
        now = max(now, n.end)

        # Reconstruct approximate previous absolute angle from generated relative angles.
        rel_main = row.get("angle")
        if isinstance(rel_main, (int, float)):
            for _ in range(int(row.get("whole", 0))):
                prev_abs = clean_angle(prev_abs + 180.0 - float(rel_main))

        rel_final = row.get("final_angle_effective")
        if isinstance(rel_final, (int, float)):
            prev_abs = clean_angle(prev_abs + 180.0 - float(rel_final))

        row["floor_end"] = floor

    return rows



def compute_lowest_floor_x(notes: list[Note]) -> int:
    values: list[int] = []
    for n in notes:
        nn = n.normalized()
        if nn.duration <= 0:
            continue
        keycount = nn.freq * nn.duration
        values.append(keycount_floor_x(keycount))
    return min(values) if values else 1




def emit_direct(angle_data, actions, floor, freq, dur, max_tiles_per_note) -> tuple[int, int, float | None]:
    if freq <= 0 or dur <= 0:
        return floor, 0, None

    bpm = freq * 60.0
    keycount = freq * dur

    whole = int(math.floor(keycount + EPS))
    frac = keycount - whole
    emitted = 0
    current_bpm: float | None = None

    if max_tiles_per_note > 0:
        whole = min(whole, max_tiles_per_note)

    if whole > 0:
        actions.append(set_bpm(floor, bpm))
        current_bpm = bpm
        for _ in range(whole):
            add_relative(angle_data, 180.0)
        floor += whole
        emitted += whole

    if frac > 1e-6 and (max_tiles_per_note <= 0 or emitted < max_tiles_per_note):
        frac_bpm = bpm / frac
        actions.append(set_bpm(floor, frac_bpm))
        current_bpm = frac_bpm
        add_relative(angle_data, 180.0)
        floor += 1
        emitted += 1

    return floor, emitted, current_bpm



def emit_angle_only(
    angle_data,
    actions,
    floor,
    freq,
    dur,
    song_bpm,
    max_tiles_per_note,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
) -> tuple[int, int, float | None, bool]:
    """
    Angle-only Hz charting.

    One global BPM is used for the generated chart, and each note's pitch is
    represented only by tile angle.

        angle = song_bpm * 180 / (freq * 60)

    No per-note SetSpeed is emitted, except optional final-tile visual
    compensation when Final tile mode is cardinal/custom.
    """
    if freq <= 0 or dur <= 0 or song_bpm <= 0:
        return floor, 0, None, False

    keycount = freq * dur
    if keycount <= EPS:
        return floor, 0, None, False

    angle = float(song_bpm) * 180.0 / max(EPS, freq * 60.0)
    angle = clean_relative_angle(angle)

    whole = int(math.floor(keycount + EPS))
    frac = keycount - math.floor(keycount)

    emitted = 0
    whole_to_emit = whole
    if max_tiles_per_note > 0:
        whole_to_emit = min(whole_to_emit, max_tiles_per_note)

    for _ in range(whole_to_emit):
        add_relative(angle_data, angle)
        floor += 1
        emitted += 1

    final_visual_used = False
    if frac > 1e-6 and (max_tiles_per_note <= 0 or emitted < max_tiles_per_note):
        scaled_final_angle = angle * frac
        prev_abs = float(angle_data[-1])
        final_angle = final_visual_angle(
            mode=final_angle_mode,
            prev_abs=prev_abs,
            scaled_final_angle=scaled_final_angle,
            custom_final_angle=final_custom_angle,
            cardinal_step=final_cardinal_step,
        )

        if final_angle <= 0:
            final_angle = scaled_final_angle

        # Keep final fractional duration = frac / freq even when visual angle changes.
        final_bpm = (freq * 60.0) * (final_angle / max(EPS, 180.0 * frac))

        if abs(final_bpm - float(song_bpm)) > 1e-6:
            actions.append(set_bpm(floor, final_bpm))
            final_visual_used = True

        add_relative(angle_data, final_angle)
        floor += 1
        emitted += 1

        # Restore the one global angle-only BPM for following tiles/pauses.
        if abs(final_bpm - float(song_bpm)) > 1e-6:
            actions.append(set_bpm(floor, song_bpm))

        if abs(final_angle - scaled_final_angle) > 1e-6:
            final_visual_used = True

    return floor, emitted, float(song_bpm), final_visual_used



def emit_angle_compression(
    angle_data,
    actions,
    floor,
    freq,
    dur,
    play_bpm,
    x_mode,
    fixed_x,
    max_tiles_per_note,
    target_angle: float | None = None,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
) -> tuple[int, int, float | None, bool, bool]:
    if freq <= 0 or dur <= 0:
        return floor, 0, None, False, False

    beat_count = dur * play_bpm / 60.0
    keycount = freq * 60.0 * beat_count / max(play_bpm, EPS)

    if keycount <= EPS:
        return floor, 0, None, False, False

    x_tiles = int(math.floor(keycount + EPS))
    frac = keycount - math.floor(keycount)

    change_x = choose_change_x(keycount, x_mode, fixed_x)
    auto_angle = 180.0 * change_x / keycount

    target_used = target_angle is not None
    angle = float(target_angle) if target_used else auto_angle
    # Keep obviously invalid values from producing impossible geometry.
    if angle <= 0:
        angle = auto_angle
        target_used = False

    # Issue #3:
    # When overriding the main zip angle, the fractional last angle should
    # be corrected by the same scale ratio.
    #
    # auto_last_angle = auto_angle * frac
    # corrected_last  = auto_last_angle * (target_angle / auto_angle)
    #                 = target_angle * frac
    #
    # If disabled, the final fractional tile uses the old auto angle.
    frac_base_angle = angle

    bpm = (freq * 60.0) * (angle / 180.0)

    actions.append(set_bpm(floor, bpm))

    emitted = 0
    whole_to_emit = x_tiles
    if max_tiles_per_note > 0:
        whole_to_emit = min(whole_to_emit, max_tiles_per_note)

    for _ in range(whole_to_emit):
        add_relative(angle_data, angle)
        floor += 1
        emitted += 1

    final_visual_used = False
    if frac > 1e-6 and (max_tiles_per_note <= 0 or emitted < max_tiles_per_note):
        scaled_final_angle = frac_base_angle * frac
        prev_abs = float(angle_data[-1])
        final_angle = final_visual_angle(
            mode=final_angle_mode,
            prev_abs=prev_abs,
            scaled_final_angle=scaled_final_angle,
            custom_final_angle=final_custom_angle,
            cardinal_step=final_cardinal_step,
        )

        # Keep the note duration correct even when the final tile angle is changed
        # for visual reasons.
        #
        # desired final-tile duration = frac / freq
        # duration(angle, bpm) = (angle / 180) * (60 / bpm)
        # => bpm = freq * 60 * angle / (180 * frac)
        if final_angle <= 0:
            final_angle = scaled_final_angle

        final_bpm = (freq * 60.0) * (final_angle / max(EPS, 180.0 * frac))

        if abs(final_bpm - bpm) > 1e-6:
            actions.append(set_bpm(floor, final_bpm))
            final_visual_used = True

        add_relative(angle_data, final_angle)
        floor += 1
        emitted += 1
        bpm = final_bpm

        if abs(final_angle - scaled_final_angle) > 1e-6:
            final_visual_used = True

    return floor, emitted, bpm, target_used, final_visual_used


def flatten_curve_notes(
    notes: list[Note],
    *,
    curve_step_sec: float = 0.025,
    curve_pitch_step: float = 0.25,
) -> list[Note]:
    out: list[Note] = []
    for n in notes:
        out.extend(
            n.sample_fixed_segments(
                max_seconds=curve_step_sec,
                max_pitch_step=curve_pitch_step,
                max_segments=2000,
            )
        )
    return out


def normalize_notes_to_first(notes: list[Note]) -> tuple[list[Note], float]:
    sorted_notes = sorted((n.normalized() for n in notes if n.duration > 0), key=lambda n: (n.start, n.midi, n.end))
    if not sorted_notes:
        return [], 0.0

    first_start = sorted_notes[0].start
    normalized = [
        Note(
            max(0.0, n.start - first_start),
            max(0.0, n.end - first_start),
            n.midi,
            n.velocity,
            n.kind,
            n.midi_end,
            n.ctrl1_midi,
            n.ctrl2_midi,
            n.target_angle,
        ).normalized()
        for n in sorted_notes
    ]
    return normalized, first_start


def export_adofai(
    notes: list[Note],
    path: str | Path,
    *,
    method: str = "rabbit_zip",
    base_bpm: float = 175.0,
    angle_only_bpm: float = 1600.0,
    rabbit_x_mode: str = "floor",
    rabbit_fixed_x: float = 8.0,
    max_tiles: int = 200000,
    max_tiles_per_note: int = 5000,
    track_visual: str = "normal",
    curve_step_sec: float = 0.025,
    curve_pitch_step: float = 0.25,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
    pretty: bool = False,
) -> dict[str, int | float | str]:
    level = new_level()
    angle_data = level["angleData"]
    actions = level["actions"]
    apply_track_visual(level, actions, track_visual)

    flattened_notes = flatten_curve_notes(notes, curve_step_sec=curve_step_sec, curve_pitch_step=curve_pitch_step)
    sorted_notes, first_note_offset = normalize_notes_to_first(flattened_notes)

    global_lowest_floor_x = compute_lowest_floor_x(sorted_notes)
    effective_fixed_x = global_lowest_floor_x if (rabbit_x_mode or "").lower().replace(" ", "_").replace("-", "_") in (
        "lowest_floor", "lowest", "min_floor", "minimum_floor"
    ) else rabbit_fixed_x

    floor = 1
    now = 0.0
    tiles = 0
    overlaps = 0
    used = 0
    target_angle_used = 0
    final_visual_corrections = 0
    current_bpm: float | None = None
    method_key = (method or "rabbit_zip").lower().replace(" ", "_").replace("-", "_")
    play_bpm = max(1e-6, float(angle_only_bpm if method_key == "angle_only" else base_bpm))

    if method_key == "angle_only":
        # One initial/global speed for the entire angle-only chart.
        # No per-note SetSpeed is needed unless final-tile visual compensation is used.
        level.setdefault("settings", {})["bpm"] = round(play_bpm, 6)
        current_bpm = play_bpm

    for n in sorted_notes:
        if max_tiles > 0 and tiles >= max_tiles:
            break

        if n.start > now + 1e-6:
            pause_seconds(actions, floor, n.start - now, current_bpm)
            now = n.start
        elif n.start < now - 1e-6:
            overlaps += 1

        audible = n.duration
        rest = 0.0

        limit = max_tiles_per_note
        if max_tiles > 0:
            remain = max_tiles - tiles
            limit = min(limit, remain) if limit > 0 else remain

        if method_key == "direct_180":
            floor, t, note_bpm = emit_direct(angle_data, actions, floor, n.freq, audible, limit)
        elif method_key == "angle_only":
            floor, t, note_bpm, final_visual_used = emit_angle_only(
                angle_data,
                actions,
                floor,
                n.freq,
                audible,
                play_bpm,
                limit,
                final_angle_mode=final_angle_mode,
                final_custom_angle=final_custom_angle,
                final_cardinal_step=final_cardinal_step,
            )
            # In angle-only mode, target_angle is intentionally ignored because
            # the angle itself determines pitch.
            if final_visual_used:
                final_visual_corrections += 1
        else:
            floor, t, note_bpm, target_used, final_visual_used = emit_angle_compression(
                angle_data,
                actions,
                floor,
                n.freq,
                audible,
                play_bpm,
                rabbit_x_mode,
                effective_fixed_x,
                limit,
                target_angle=n.target_angle,
                final_angle_mode=final_angle_mode,
                final_custom_angle=final_custom_angle,
                final_cardinal_step=final_cardinal_step,
            )
            if target_used:
                target_angle_used += 1
            if final_visual_used:
                final_visual_corrections += 1

        if note_bpm is not None:
            current_bpm = note_bpm

        tiles += t
        used += 1

        now = max(now, n.end)

    text = json.dumps(level, ensure_ascii=False, indent=2 if pretty else None, separators=None if pretty else (",", ":"))
    Path(path).write_text(text, encoding="utf-8")

    return {
        "method": method_key,
        "track_visual": track_visual,
        "curve_step_sec": round(float(curve_step_sec), 6),
        "curve_pitch_step": round(float(curve_pitch_step), 6),
        "input_notes_total": len(notes),
        "base_bpm": round(float(base_bpm), 6),
        "angle_only_bpm": round(float(angle_only_bpm), 6),
        "effective_play_bpm": round(float(play_bpm), 6),
        "lowest_floor_x": global_lowest_floor_x,
        "effective_fixed_x": round(float(effective_fixed_x), 6),
        "first_note_offset_seconds": round(first_note_offset, 6),
        "start_floor": 1,
        "notes_total": len(sorted_notes),
        "notes_used": used,
        "target_angle_ignored": sum(1 for n in sorted_notes if method_key == "angle_only" and n.target_angle is not None),
        "target_angle_used": target_angle_used,
        "final_angle_mode": final_angle_mode,
        "final_custom_angle": round(float(final_custom_angle), 6),
        "final_cardinal_step": round(float(final_cardinal_step), 6),
        "final_visual_corrections": final_visual_corrections,
        "overlaps_serialized": overlaps,
        "tiles_total": tiles,
        "floors_total": len(angle_data) - 1,
        "actions_total": len(actions),
    }
