from __future__ import annotations

from pathlib import Path
import json
import math
from typing import Any
from note_model import Note, note_name

EPS = 1e-9


def new_level() -> dict[str, Any]:
    return {
        "settings": {
            "version": 15,
            "artist": "AdopyHzEditor",
            "songFilename": "Hz Chart",
            "songOffset": 0,
            "author": "AdopyHzEditor",
            "separateCountdownTime": "Enabled",
            "previewImage": "",
            "previewIcon": "",
            "previewIconColor": "003f52",
            "previewSongStart": 0,
            "previewSongDuration": 10,
            "seizureWarning": "Disabled",
            "levelDesc": "Generated by AdopyHzEditor",
            "levelTags": "Hz Chart",
            "artistLinks": "",
            "speedTrialAim": 0,
            "difficulty": 1,
            "requiredMods": [],
        },
        # floor 0 is a clean starter tile. Hz generation starts at floor 1.
        "angleData": [0, 0],
        "actions": [],
        "decorations": [],
    }


def clean_angle(x: float) -> int | float:
    x %= 360.0
    if abs(x - round(x)) < 1e-9:
        return int(round(x)) % 360
    return round(x, 9)


def clean_relative_angle(x: float) -> float:
    """
    Relative angle for generated ADOFAI tiles.
    Avoid exact 0 because it can create awkward/ambiguous U-turn-like geometry.
    """
    v = float(x) % 360.0
    if abs(v) < 1e-9:
        v = 360.0
    return round(v, 9)


def nearest_cardinal_angle(abs_angle: float, step: float = 90.0) -> float:
    step = max(1e-6, float(step))
    return clean_angle(round(float(abs_angle) / step) * step)


def final_visual_angle(
    *,
    mode: str,
    prev_abs: float,
    scaled_final_angle: float,
    custom_final_angle: float,
    cardinal_step: float = 90.0,
) -> float:
    """
    Choose the visual final-tile relative angle.

    scaled:
        current mathematically scaled fractional angle.
    straight:
        legacy alias for custom 180. Not exposed in the UI.
    cardinal:
        choose a relative angle that makes the final absolute tile direction snap
        to the nearest cardinal/grid direction.
    custom:
        use user-specified relative angle.
    """
    mode = (mode or "scaled").lower().replace(" ", "_").replace("-", "_")

    if mode in ("straight", "straight_relative"):
        return 180.0

    if mode in ("custom", "custom_relative"):
        return clean_relative_angle(custom_final_angle)

    if mode in ("cardinal", "snap_cardinal", "snap_to_cardinal"):
        scaled_abs = clean_angle(prev_abs + 180.0 - scaled_final_angle)
        desired_abs = nearest_cardinal_angle(scaled_abs, cardinal_step)
        return clean_relative_angle(prev_abs + 180.0 - desired_abs)

    return float(scaled_final_angle)


def add_relative(angle_data: list[Any], rel: float) -> None:
    prev = float(angle_data[-1])
    cur = prev + 180.0 - float(rel)
    angle_data.append(clean_angle(cur))


def speed_event_floor(floor: int) -> int:
    """
    ADOFAI editor visually shows the speed event on the corner/transition tile
    when placed at the generation floor.

    The requested placement is the next Hz section tile, so speed events are
    written one floor later. floor 0 still stays clean.
    """
    return max(1, int(floor) + 1)


def set_bpm(floor: int, bpm: float) -> dict[str, Any]:
    return {
        "floor": speed_event_floor(floor),
        "eventType": "SetSpeed",
        "speedType": "Bpm",
        "beatsPerMinute": round(float(bpm), 6),
        "bpmMultiplier": 1,
    }


def pause_beats(floor: int, beats: float) -> dict[str, Any]:
    return {
        "floor": int(floor),
        "eventType": "Pause",
        "duration": round(max(0.0, float(beats)), 6),
        "countdownTicks": 0,
        "angleCorrectionDir": -1,
    }


def track_color_for_visual(track_visual: str) -> tuple[str, str]:
    """
    Return (trackColor, secondaryTrackColor).
    Alpha is the last byte: RRGGBBAA.
    """
    mode = (track_visual or "normal").lower()

    if mode == "hidden":
        return "debb7b00", "ffffff00"
    if mode == "very faint":
        return "debb7b18", "ffffff10"
    if mode == "faint":
        return "debb7b40", "ffffff22"

    return "debb7bff", "ffffffff"


def color_track_event(floor: int, track_visual: str) -> dict[str, Any]:
    track, secondary = track_color_for_visual(track_visual)
    return {
        "floor": int(floor),
        "eventType": "ColorTrack",
        "trackColorType": "Single",
        "trackColor": track,
        "secondaryTrackColor": secondary,
        "trackColorAnimDuration": 0,
        "trackColorPulse": "None",
        "trackPulseLength": 10,
        "trackStyle": "Standard",
        "trackTexture": "",
        "trackTextureScale": 1,
        "trackAnimation": "None",
        "beatsAhead": 3,
        "trackDisappearanceAnimation": "None",
        "beatsBehind": 4,
    }


def apply_track_visual(level: dict[str, Any], actions: list[dict[str, Any]], track_visual: str) -> None:
    mode = (track_visual or "normal").lower()
    track, secondary = track_color_for_visual(mode)

    settings = level.setdefault("settings", {})
    settings["trackColorType"] = "Single"
    settings["trackColor"] = track
    settings["secondaryTrackColor"] = secondary
    settings["trackColorAnimDuration"] = 0
    settings["trackColorPulse"] = "None"
    settings["trackPulseLength"] = 10
    settings["trackStyle"] = "Standard"

    if mode != "normal":
        actions.append(color_track_event(0, mode))


def pause_seconds(actions: list[dict[str, Any]], floor: int, seconds: float, current_bpm: float | None) -> None:
    if seconds <= 1e-6:
        return
    bpm = max(1e-6, float(current_bpm or 120.0))
    actions.append(pause_beats(floor, seconds * bpm / 60.0))


def keycount_floor_x(keycount: float) -> int:
    return max(1, int(math.floor(max(0.0, keycount) + EPS)))


def choose_change_x(keycount: float, mode: str, fixed: float) -> float:
    x_floor = keycount_floor_x(keycount)
    mode = (mode or "floor").lower().replace(" ", "_").replace("-", "_")

    if mode == "fixed":
        return max(0.000001, float(fixed))
    if mode in ("lowest_floor", "lowest", "min_floor", "minimum_floor"):
        return max(1.0, float(fixed))
    if mode == "round":
        return max(1.0, float(round(keycount)))
    if mode == "ceil":
        return max(1.0, float(math.ceil(keycount)))

    return max(1.0, float(x_floor))


def build_adofai_debug_rows(
    notes: list[Note],
    *,
    method: str = "rabbit_zip",
    base_bpm: float = 175.0,
    angle_only_bpm: float = 1600.0,
    rabbit_x_mode: str = "floor",
    rabbit_fixed_x: float = 8.0,
    max_tiles: int = 200000,
    max_tiles_per_note: int = 5000,
    curve_step_sec: float = 0.025,
    curve_pitch_step: float = 0.25,
    phase_continuous_glide: bool = True,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
    **_: Any,
) -> list[dict[str, Any]]:
    """
    Build a per-note / per-zip calculation preview for ADOFAI Hz export.

    This does not write a file. It mirrors the export calculations enough to
    make angle/BPM/keycount issues visible before exporting.
    """
    method_key = (method or "rabbit_zip").lower().replace(" ", "_").replace("-", "_")
    use_phase_continuous_glide = bool(phase_continuous_glide)

    if use_phase_continuous_glide:
        prepared_notes = [n.normalized() for n in notes if n.duration > 0]
    else:
        prepared_notes = flatten_curve_notes(notes, curve_step_sec=curve_step_sec, curve_pitch_step=curve_pitch_step)

    sorted_notes, first_note_offset = normalize_notes_to_first(prepared_notes)

    play_bpm = max(1e-6, float(angle_only_bpm if method_key == "angle_only" else base_bpm))

    global_lowest_floor_x = compute_lowest_floor_x(sorted_notes)
    effective_fixed_x = global_lowest_floor_x if (rabbit_x_mode or "").lower().replace(" ", "_").replace("-", "_") in (
        "lowest_floor", "lowest", "min_floor", "minimum_floor"
    ) else rabbit_fixed_x

    rows: list[dict[str, Any]] = []
    floor = 1
    now = 0.0
    tiles_so_far = 0
    prev_abs = 0.0

    for idx, n in enumerate(sorted_notes):
        if max_tiles > 0 and tiles_so_far >= max_tiles:
            break

        freq = float(n.freq)
        dur = float(n.duration)
        if freq <= 0 or dur <= 0:
            continue

        pause_seconds_before = max(0.0, n.start - now)
        overlap = n.start < now - 1e-6

        limit = max_tiles_per_note
        if max_tiles > 0:
            remain = max_tiles - tiles_so_far
            limit = min(limit, remain) if limit > 0 else remain

        row: dict[str, Any] = {
            "index": idx,
            "floor_start": floor,
            "start_s": round(n.start, 6),
            "end_s": round(n.end, 6),
            "duration_s": round(dur, 6),
            "pause_before_s": round(pause_seconds_before, 6),
            "overlap": bool(overlap),
            "kind": n.kind,
            "interpolation": "" if n.interpolation == "bezier_pitch" and not n.is_curve else n.interpolation,
            "note": note_name(n.midi),
            "midi": round(float(n.midi), 6),
            "freq_hz": round(freq, 6),
            "method": method_key,
            "target_angle": "" if n.target_angle is None else round(float(n.target_angle), 6),
            "target_angle_used": False,
            "target_angle_ignored": bool(method_key == "angle_only" and n.target_angle is not None),
            "warning": "",
        }

        emitted = 0
        final_visual_used = False
        final_bpm = ""
        effective_bpm = ""

        if method_key == "direct_180":
            if use_phase_continuous_glide and n.is_curve:
                intervals, total_phase = curve_phase_dt_intervals(n)
                if limit > 0:
                    intervals = intervals[:limit]
                emitted = len(intervals)
                whole = int(math.floor(total_phase + EPS))
                frac = total_phase - math.floor(total_phase)
                bpms = [60.0 / max(EPS, dt) for dt in intervals]
                final_bpm = bpms[-1] if bpms else ""
                final_visual_used = False
                angle_sequence = [180.0 for _ in intervals]
                effective_final = 180.0 if intervals else ""

                if intervals:
                    prev_before_final = prev_abs
                    for rel in angle_sequence[:-1]:
                        prev_before_final = clean_angle(prev_before_final + 180.0 - float(rel))
                    adjusted_final = final_visual_angle(
                        mode=final_angle_mode,
                        prev_abs=prev_before_final,
                        scaled_final_angle=180.0,
                        custom_final_angle=final_custom_angle,
                        cardinal_step=final_cardinal_step,
                    )
                    if adjusted_final > 0 and abs(float(adjusted_final) - 180.0) > 1e-6:
                        effective_final = adjusted_final
                        final_bpm = float(adjusted_final) * 60.0 / max(EPS, 180.0 * intervals[-1])
                        angle_sequence[-1] = adjusted_final
                        final_visual_used = True

                row.update({
                    "phase_continuous": True,
                    "keycount": round(total_phase, 6),
                    "whole": whole,
                    "frac": round(frac, 6),
                    "change_x": "",
                    "angle": 180.0,
                    "angle_min": 180.0,
                    "angle_max": 180.0,
                    "auto_angle": 180.0,
                    "final_angle_scaled": 180.0 if intervals else "",
                    "final_angle_effective": "" if effective_final == "" else round(float(effective_final), 6),
                    "effective_bpm": "varies",
                    "final_bpm": "" if final_bpm == "" else round(float(final_bpm), 6),
                    "tiles_est": emitted,
                    "final_visual_used": bool(final_visual_used),
                    "lowest_floor_x": global_lowest_floor_x,
                    "effective_fixed_x": round(float(effective_fixed_x), 6),
                    "_angle_sequence": angle_sequence,
                })
            else:
                bpm = freq * 60.0
                keycount = freq * dur
                whole = int(math.floor(keycount + EPS))
                frac = keycount - whole
                emitted = whole
                if limit > 0:
                    emitted = min(emitted, limit)

                final_angle = 180.0 if frac > 1e-6 and (limit <= 0 or emitted < limit) else ""
                final_bpm = (bpm / frac) if isinstance(final_angle, float) and frac > 1e-6 else ""
                if isinstance(final_angle, float):
                    emitted += 1

                row.update({
                    "keycount": round(keycount, 6),
                    "whole": whole,
                    "frac": round(frac, 6),
                    "change_x": "",
                    "phase_continuous": False,
                    "angle": 180.0,
                    "angle_min": 180.0,
                    "angle_max": 180.0,
                    "auto_angle": 180.0,
                    "final_angle_scaled": "" if frac <= 1e-6 else round(180.0 * frac, 6),
                    "final_angle_effective": final_angle if final_angle == "" else round(final_angle, 6),
                    "effective_bpm": round(bpm, 6),
                    "final_bpm": "" if final_bpm == "" else round(float(final_bpm), 6),
                    "tiles_est": emitted,
                    "final_visual_used": False,
                    "lowest_floor_x": global_lowest_floor_x,
                    "effective_fixed_x": round(float(effective_fixed_x), 6),
                })

        elif method_key == "angle_only":
            if use_phase_continuous_glide and n.is_curve:
                angles, total_phase = angle_only_curve_intervals(n, play_bpm)
                if limit > 0:
                    angles = angles[:limit]

                emitted = len(angles)
                whole = int(math.floor(total_phase + EPS))
                frac = total_phase - math.floor(total_phase)

                angle_min = min(angles) if angles else ""
                angle_max = max(angles) if angles else ""
                scaled_final = angles[-1] if angles else ""
                effective_final = scaled_final
                final_bpm = ""
                final_visual_used = False
                angle_sequence = list(angles)

                if angles:
                    prev_before_final = prev_abs
                    for rel in angles[:-1]:
                        prev_before_final = clean_angle(prev_before_final + 180.0 - float(rel))

                    adjusted_final = final_visual_angle(
                        mode=final_angle_mode,
                        prev_abs=prev_before_final,
                        scaled_final_angle=angles[-1],
                        custom_final_angle=final_custom_angle,
                        cardinal_step=final_cardinal_step,
                    )
                    if adjusted_final <= 0:
                        adjusted_final = angles[-1]

                    if abs(float(adjusted_final) - float(angles[-1])) > 1e-6:
                        final_bpm = play_bpm * float(adjusted_final) / max(EPS, float(angles[-1]))
                        effective_final = adjusted_final
                        angle_sequence[-1] = adjusted_final
                        final_visual_used = True

                row.update({
                    "phase_continuous": True,
                    "keycount": round(total_phase, 6),
                    "whole": whole,
                    "frac": round(frac, 6),
                    "change_x": "",
                    "angle": "varies",
                    "angle_min": "" if angle_min == "" else round(float(angle_min), 6),
                    "angle_max": "" if angle_max == "" else round(float(angle_max), 6),
                    "auto_angle": "varies",
                    "final_angle_scaled": "" if scaled_final == "" else round(float(scaled_final), 6),
                    "final_angle_effective": "" if effective_final == "" else round(float(effective_final), 6),
                    "effective_bpm": round(play_bpm, 6),
                    "final_bpm": "" if final_bpm == "" else round(float(final_bpm), 6),
                    "tiles_est": emitted,
                    "final_visual_used": bool(final_visual_used),
                    "lowest_floor_x": global_lowest_floor_x,
                    "effective_fixed_x": round(float(effective_fixed_x), 6),
                    "_angle_sequence": angle_sequence,
                })
            else:
                keycount = freq * dur
                whole = int(math.floor(keycount + EPS))
                frac = keycount - math.floor(keycount)
                angle = clean_relative_angle(play_bpm * 180.0 / max(EPS, freq * 60.0))

                emitted = whole
                if limit > 0:
                    emitted = min(emitted, limit)

                scaled_final = angle * frac if frac > 1e-6 else ""
                effective_final = ""
                if frac > 1e-6 and (limit <= 0 or emitted < limit):
                    effective_final = final_visual_angle(
                        mode=final_angle_mode,
                        prev_abs=prev_abs,
                        scaled_final_angle=angle * frac,
                        custom_final_angle=final_custom_angle,
                        cardinal_step=final_cardinal_step,
                    )
                    final_bpm = (freq * 60.0) * (effective_final / max(EPS, 180.0 * frac))
                    final_visual_used = abs(float(effective_final) - float(angle * frac)) > 1e-6 or abs(final_bpm - play_bpm) > 1e-6
                    emitted += 1

                row.update({
                    "phase_continuous": False,
                    "keycount": round(keycount, 6),
                    "whole": whole,
                    "frac": round(frac, 6),
                    "change_x": "",
                    "angle": round(angle, 6),
                    "angle_min": round(angle, 6),
                    "angle_max": round(angle, 6),
                    "auto_angle": round(angle, 6),
                    "final_angle_scaled": "" if scaled_final == "" else round(float(scaled_final), 6),
                    "final_angle_effective": "" if effective_final == "" else round(float(effective_final), 6),
                    "effective_bpm": round(play_bpm, 6),
                    "final_bpm": "" if final_bpm == "" else round(float(final_bpm), 6),
                    "tiles_est": emitted,
                    "final_visual_used": bool(final_visual_used),
                    "lowest_floor_x": global_lowest_floor_x,
                    "effective_fixed_x": round(float(effective_fixed_x), 6),
                })

        else:
            if use_phase_continuous_glide and n.is_curve:
                intervals, total_phase = curve_phase_dt_intervals(n)
                if limit > 0:
                    intervals = intervals[:limit]

                whole = int(math.floor(total_phase + EPS))
                frac = total_phase - math.floor(total_phase)
                change_x = choose_change_x(total_phase, rabbit_x_mode, effective_fixed_x)
                auto_angle = 180.0 * change_x / max(EPS, total_phase)

                target_used = n.target_angle is not None and float(n.target_angle) > 0
                angle = float(n.target_angle) if target_used else auto_angle

                emitted = len(intervals)
                angle_sequence: list[float] = []
                bpms: list[float] = []
                final_visual_used = False
                scaled_final = ""
                effective_final = ""

                for i, dt in enumerate(intervals):
                    is_final = i == len(intervals) - 1
                    rel = angle
                    if is_final and frac > 1e-6:
                        scaled_final = angle * frac
                        rel = scaled_final

                        prev_before_final = prev_abs
                        for prev_rel in angle_sequence:
                            prev_before_final = clean_angle(prev_before_final + 180.0 - float(prev_rel))

                        adjusted = final_visual_angle(
                            mode=final_angle_mode,
                            prev_abs=prev_before_final,
                            scaled_final_angle=scaled_final,
                            custom_final_angle=final_custom_angle,
                            cardinal_step=final_cardinal_step,
                        )
                        if adjusted > 0:
                            rel = adjusted
                        effective_final = rel
                        if abs(float(rel) - float(scaled_final)) > 1e-6:
                            final_visual_used = True

                    angle_sequence.append(rel)
                    bpms.append(rel * 60.0 / max(EPS, 180.0 * dt))

                if not effective_final and angle_sequence:
                    effective_final = angle_sequence[-1]

                row.update({
                    "phase_continuous": True,
                    "keycount": round(total_phase, 6),
                    "whole": whole,
                    "frac": round(frac, 6),
                    "change_x": round(float(change_x), 6),
                    "angle": round(angle, 6),
                    "angle_min": round(min(angle_sequence), 6) if angle_sequence else "",
                    "angle_max": round(max(angle_sequence), 6) if angle_sequence else "",
                    "auto_angle": round(auto_angle, 6),
                    "final_angle_scaled": "" if scaled_final == "" else round(float(scaled_final), 6),
                    "final_angle_effective": "" if effective_final == "" else round(float(effective_final), 6),
                    "effective_bpm": "varies",
                    "final_bpm": "" if not bpms else round(float(bpms[-1]), 6),
                    "tiles_est": emitted,
                    "target_angle_used": bool(target_used),
                    "final_visual_used": bool(final_visual_used),
                    "lowest_floor_x": global_lowest_floor_x,
                    "effective_fixed_x": round(float(effective_fixed_x), 6),
                    "_angle_sequence": angle_sequence,
                })
            else:
                beat_count = dur * play_bpm / 60.0
                keycount = freq * 60.0 * beat_count / max(play_bpm, EPS)
                whole = int(math.floor(keycount + EPS))
                frac = keycount - math.floor(keycount)

                change_x = choose_change_x(keycount, rabbit_x_mode, effective_fixed_x)
                auto_angle = 180.0 * change_x / keycount if keycount > EPS else 180.0

                target_used = n.target_angle is not None and float(n.target_angle) > 0
                angle = float(n.target_angle) if target_used else auto_angle
                bpm = (freq * 60.0) * (angle / 180.0)

                emitted = whole
                if limit > 0:
                    emitted = min(emitted, limit)

                scaled_final = angle * frac if frac > 1e-6 else ""
                effective_final = ""
                if frac > 1e-6 and (limit <= 0 or emitted < limit):
                    effective_final = final_visual_angle(
                        mode=final_angle_mode,
                        prev_abs=prev_abs,
                        scaled_final_angle=angle * frac,
                        custom_final_angle=final_custom_angle,
                        cardinal_step=final_cardinal_step,
                    )
                    final_bpm = (freq * 60.0) * (effective_final / max(EPS, 180.0 * frac))
                    final_visual_used = abs(float(effective_final) - float(angle * frac)) > 1e-6 or abs(final_bpm - bpm) > 1e-6
                    emitted += 1

                row.update({
                    "keycount": round(keycount, 6),
                    "whole": whole,
                    "frac": round(frac, 6),
                    "change_x": round(float(change_x), 6),
                    "phase_continuous": False,
                    "angle": round(angle, 6),
                    "angle_min": round(angle, 6),
                    "angle_max": round(angle, 6),
                    "auto_angle": round(auto_angle, 6),
                    "final_angle_scaled": "" if scaled_final == "" else round(float(scaled_final), 6),
                    "final_angle_effective": "" if effective_final == "" else round(float(effective_final), 6),
                    "effective_bpm": round(bpm, 6),
                    "final_bpm": "" if final_bpm == "" else round(float(final_bpm), 6),
                    "tiles_est": emitted,
                    "target_angle_used": bool(target_used),
                    "final_visual_used": bool(final_visual_used),
                    "lowest_floor_x": global_lowest_floor_x,
                    "effective_fixed_x": round(float(effective_fixed_x), 6),
                })

        if limit > 0 and row.get("whole", 0) > limit:
            row["warning"] = f"clipped by max_tiles_per_note={limit}"
        angle_for_warning = row.get("angle_min", row.get("angle"))
        if angle_for_warning != "" and isinstance(angle_for_warning, (int, float)) and float(angle_for_warning) < 1.0:
            row["warning"] = (row["warning"] + "; " if row["warning"] else "") + "very small angle"

        rows.append(row)

        # Approximate floor/abs angle progression for next debug row.
        floor += int(row.get("tiles_est", 0))
        tiles_so_far += int(row.get("tiles_est", 0))
        now = max(now, n.end)

        # Reconstruct approximate previous absolute angle from generated relative angles.
        seq = row.get("_angle_sequence")
        if isinstance(seq, list):
            for rel in seq:
                if isinstance(rel, (int, float)):
                    prev_abs = clean_angle(prev_abs + 180.0 - float(rel))
        else:
            rel_main = row.get("angle")
            if isinstance(rel_main, (int, float)):
                for _ in range(int(row.get("whole", 0))):
                    prev_abs = clean_angle(prev_abs + 180.0 - float(rel_main))

            rel_final = row.get("final_angle_effective")
            if isinstance(rel_final, (int, float)):
                prev_abs = clean_angle(prev_abs + 180.0 - float(rel_final))

        row["floor_end"] = floor

    return rows



def compute_lowest_floor_x(notes: list[Note]) -> int:
    values: list[int] = []
    for n in notes:
        nn = n.normalized()
        if nn.duration <= 0:
            continue
        keycount = nn.freq * nn.duration
        values.append(keycount_floor_x(keycount))
    return min(values) if values else 1




def curve_phase_samples(
    note: Note,
    *,
    samples_per_second: float = 2400.0,
    min_samples: int = 128,
    max_samples: int = 80000,
) -> tuple[list[float], list[float], float]:
    """
    Sample cumulative phase for one continuous curve/glide note.

    phase(t) = integral frequency(t) dt
    Unit: cycles.
    """
    n = note.normalized()
    dur = n.duration
    if dur <= 0:
        return [0.0], [0.0], 0.0

    # More samples for longer notes and large pitch movement, but keep bounded.
    probe = [n.freq_at(i / 16.0) for i in range(17)]
    f_min = max(1e-9, min(probe))
    f_max = max(probe)
    freq_ratio = max(1.0, f_max / f_min)
    base_count = int(math.ceil(dur * samples_per_second))
    extra = int(math.ceil(math.log2(freq_ratio + 1.0) * 128))
    count = max(min_samples, base_count + extra)
    count = min(max_samples, max(2, count))

    times = [dur * i / count for i in range(count + 1)]
    phases = [0.0] * (count + 1)

    prev_f = n.freq_at(0.0)
    accum = 0.0
    for i in range(1, count + 1):
        u = i / count
        cur_f = n.freq_at(u)
        dt = times[i] - times[i - 1]
        accum += (prev_f + cur_f) * 0.5 * dt
        phases[i] = accum
        prev_f = cur_f

    return times, phases, accum


def invert_phase_time(times: list[float], phases: list[float], target_phase: float, start_index: int = 0) -> tuple[float, int]:
    """
    Return approximate t where cumulative phase reaches target_phase.
    Linear interpolation is enough because samples are dense.
    """
    if not times or not phases:
        return 0.0, 0

    i = max(1, int(start_index))
    while i < len(phases) and phases[i] < target_phase:
        i += 1

    if i >= len(phases):
        return times[-1], len(phases) - 1

    p0 = phases[i - 1]
    p1 = phases[i]
    t0 = times[i - 1]
    t1 = times[i]

    if abs(p1 - p0) < EPS:
        return t1, i

    a = (target_phase - p0) / (p1 - p0)
    a = max(0.0, min(1.0, a))
    return t0 + (t1 - t0) * a, i


def curve_phase_dt_intervals(note: Note) -> tuple[list[float], float]:
    """
    Convert a continuous curve/glide into time intervals between phase cycles.

    The returned intervals cover the entire note duration. Full-cycle intervals
    come first; if the curve ends mid-cycle, the final partial interval is also
    included.
    """
    n = note.normalized()
    if n.duration <= 0:
        return [], 0.0

    times, phases, total_phase = curve_phase_samples(n)
    if total_phase <= EPS:
        return [], 0.0

    targets = list(range(1, int(math.floor(total_phase + EPS)) + 1))
    tile_times: list[float] = []
    scan = 1
    for target in targets:
        t, scan = invert_phase_time(times, phases, float(target), scan)
        if not tile_times or t > tile_times[-1] + 1e-10:
            tile_times.append(t)

    if n.duration > (tile_times[-1] if tile_times else 0.0) + 1e-9:
        tile_times.append(n.duration)

    intervals: list[float] = []
    prev_t = 0.0
    for t in tile_times:
        dt = max(0.0, t - prev_t)
        if dt > 1e-12:
            intervals.append(dt)
        prev_t = t

    return intervals, total_phase


def angle_only_curve_intervals(note: Note, song_bpm: float) -> tuple[list[float], float]:
    """
    Convert a continuous curve/glide to tile relative angles for Angle-only mode.
    """
    if song_bpm <= 0:
        return [], 0.0

    intervals, total_phase = curve_phase_dt_intervals(note)
    out = [
        clean_relative_angle(dt * float(song_bpm) * 180.0 / 60.0)
        for dt in intervals
    ]
    return out, total_phase


def emit_angle_only_curve_continuous(
    angle_data,
    actions,
    floor,
    note: Note,
    song_bpm,
    max_tiles_per_note,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
) -> tuple[int, int, float | None, bool, float]:
    """
    Phase-continuous angle-only export for Curve/Glide notes.
    """
    if note.duration <= 0 or song_bpm <= 0:
        return floor, 0, None, False, 0.0

    angles, total_phase = angle_only_curve_intervals(note, song_bpm)
    if not angles:
        return floor, 0, None, False, total_phase

    if max_tiles_per_note > 0:
        angles = angles[:max_tiles_per_note]

    final_visual_used = False
    emitted = 0

    for i, rel in enumerate(angles):
        is_final = i == len(angles) - 1
        final_rel = rel

        if is_final:
            prev_abs = float(angle_data[-1])
            adjusted = final_visual_angle(
                mode=final_angle_mode,
                prev_abs=prev_abs,
                scaled_final_angle=rel,
                custom_final_angle=final_custom_angle,
                cardinal_step=final_cardinal_step,
            )

            if adjusted <= 0:
                adjusted = rel

            if abs(float(adjusted) - float(rel)) > 1e-6:
                # Preserve the actual final interval duration represented by rel.
                # duration(rel, song_bpm) == duration(adjusted, final_bpm)
                final_bpm = float(song_bpm) * float(adjusted) / max(EPS, float(rel))
                actions.append(set_bpm(floor, final_bpm))
                final_visual_used = True
                final_rel = adjusted

        add_relative(angle_data, final_rel)
        floor += 1
        emitted += 1

        if is_final and final_visual_used:
            actions.append(set_bpm(floor, song_bpm))

    return floor, emitted, float(song_bpm), final_visual_used, total_phase


def emit_direct_curve_continuous(
    angle_data,
    actions,
    floor,
    note: Note,
    max_tiles_per_note,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
) -> tuple[int, int, float | None, bool, float]:
    """
    Phase-continuous Direct 180 export for Curve/Glide notes.

    The pitch curve controls timing. Each tile remains 180°, and SetSpeed is
    emitted per tile so each interval has the correct duration.
    """
    intervals, total_phase = curve_phase_dt_intervals(note)
    if not intervals:
        return floor, 0, None, False, total_phase

    if max_tiles_per_note > 0:
        intervals = intervals[:max_tiles_per_note]

    emitted = 0
    current_bpm: float | None = None
    final_visual_used = False

    for i, dt in enumerate(intervals):
        rel = 180.0
        is_final = i == len(intervals) - 1

        if is_final:
            prev_abs = float(angle_data[-1])
            adjusted = final_visual_angle(
                mode=final_angle_mode,
                prev_abs=prev_abs,
                scaled_final_angle=rel,
                custom_final_angle=final_custom_angle,
                cardinal_step=final_cardinal_step,
            )
            if adjusted > 0:
                rel = adjusted

        bpm = rel * 60.0 / max(EPS, 180.0 * dt)
        actions.append(set_bpm(floor, bpm))
        current_bpm = bpm

        if is_final and abs(rel - 180.0) > 1e-6:
            final_visual_used = True

        add_relative(angle_data, rel)
        floor += 1
        emitted += 1

    return floor, emitted, current_bpm, final_visual_used, total_phase


def emit_angle_compression_curve_continuous(
    angle_data,
    actions,
    floor,
    note: Note,
    play_bpm,
    x_mode,
    fixed_x,
    max_tiles_per_note,
    target_angle: float | None = None,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
) -> tuple[int, int, float | None, bool, bool, float]:
    """
    Phase-continuous Angle Compression export for Curve/Glide notes.

    The curve is not split into short fixed-Hz notes. Instead, f(t) is
    integrated and one tile is placed per accumulated cycle. The main visual
    angle is chosen from total keycount, then SetSpeed per tile preserves the
    exact interval duration.
    """
    intervals, total_phase = curve_phase_dt_intervals(note)
    if not intervals or total_phase <= EPS:
        return floor, 0, None, False, False, total_phase

    if max_tiles_per_note > 0:
        intervals = intervals[:max_tiles_per_note]

    whole = int(math.floor(total_phase + EPS))
    frac = total_phase - math.floor(total_phase)

    change_x = choose_change_x(total_phase, x_mode, fixed_x)
    auto_angle = 180.0 * change_x / max(EPS, total_phase)

    target_used = target_angle is not None
    main_angle = float(target_angle) if target_used else auto_angle
    if main_angle <= 0:
        main_angle = auto_angle
        target_used = False

    emitted = 0
    current_bpm: float | None = None
    final_visual_used = False

    for i, dt in enumerate(intervals):
        is_final = i == len(intervals) - 1
        rel = main_angle

        # If the note ends mid-cycle, the last tile is the fractional visual tile.
        if is_final and frac > 1e-6:
            rel = main_angle * frac
            prev_abs = float(angle_data[-1])
            adjusted = final_visual_angle(
                mode=final_angle_mode,
                prev_abs=prev_abs,
                scaled_final_angle=rel,
                custom_final_angle=final_custom_angle,
                cardinal_step=final_cardinal_step,
            )
            if adjusted > 0:
                rel = adjusted

            if abs(rel - main_angle * frac) > 1e-6:
                final_visual_used = True

        bpm = rel * 60.0 / max(EPS, 180.0 * dt)
        actions.append(set_bpm(floor, bpm))
        current_bpm = bpm

        add_relative(angle_data, rel)
        floor += 1
        emitted += 1

    return floor, emitted, current_bpm, target_used, final_visual_used, total_phase


def emit_direct(angle_data, actions, floor, freq, dur, max_tiles_per_note) -> tuple[int, int, float | None]:
    if freq <= 0 or dur <= 0:
        return floor, 0, None

    bpm = freq * 60.0
    keycount = freq * dur

    whole = int(math.floor(keycount + EPS))
    frac = keycount - whole
    emitted = 0
    current_bpm: float | None = None

    if max_tiles_per_note > 0:
        whole = min(whole, max_tiles_per_note)

    if whole > 0:
        actions.append(set_bpm(floor, bpm))
        current_bpm = bpm
        for _ in range(whole):
            add_relative(angle_data, 180.0)
        floor += whole
        emitted += whole

    if frac > 1e-6 and (max_tiles_per_note <= 0 or emitted < max_tiles_per_note):
        frac_bpm = bpm / frac
        actions.append(set_bpm(floor, frac_bpm))
        current_bpm = frac_bpm
        add_relative(angle_data, 180.0)
        floor += 1
        emitted += 1

    return floor, emitted, current_bpm



def emit_angle_only(
    angle_data,
    actions,
    floor,
    freq,
    dur,
    song_bpm,
    max_tiles_per_note,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
) -> tuple[int, int, float | None, bool]:
    """
    Angle-only Hz charting.

    One global BPM is used for the generated chart, and each note's pitch is
    represented only by tile angle.

        angle = song_bpm * 180 / (freq * 60)

    No per-note SetSpeed is emitted, except optional final-tile visual
    compensation when Final tile mode is cardinal/custom.
    """
    if freq <= 0 or dur <= 0 or song_bpm <= 0:
        return floor, 0, None, False

    keycount = freq * dur
    if keycount <= EPS:
        return floor, 0, None, False

    angle = float(song_bpm) * 180.0 / max(EPS, freq * 60.0)
    angle = clean_relative_angle(angle)

    whole = int(math.floor(keycount + EPS))
    frac = keycount - math.floor(keycount)

    emitted = 0
    whole_to_emit = whole
    if max_tiles_per_note > 0:
        whole_to_emit = min(whole_to_emit, max_tiles_per_note)

    for _ in range(whole_to_emit):
        add_relative(angle_data, angle)
        floor += 1
        emitted += 1

    final_visual_used = False
    if frac > 1e-6 and (max_tiles_per_note <= 0 or emitted < max_tiles_per_note):
        scaled_final_angle = angle * frac
        prev_abs = float(angle_data[-1])
        final_angle = final_visual_angle(
            mode=final_angle_mode,
            prev_abs=prev_abs,
            scaled_final_angle=scaled_final_angle,
            custom_final_angle=final_custom_angle,
            cardinal_step=final_cardinal_step,
        )

        if final_angle <= 0:
            final_angle = scaled_final_angle

        # Keep final fractional duration = frac / freq even when visual angle changes.
        final_bpm = (freq * 60.0) * (final_angle / max(EPS, 180.0 * frac))

        if abs(final_bpm - float(song_bpm)) > 1e-6:
            actions.append(set_bpm(floor, final_bpm))
            final_visual_used = True

        add_relative(angle_data, final_angle)
        floor += 1
        emitted += 1

        # Restore the one global angle-only BPM for following tiles/pauses.
        if abs(final_bpm - float(song_bpm)) > 1e-6:
            actions.append(set_bpm(floor, song_bpm))

        if abs(final_angle - scaled_final_angle) > 1e-6:
            final_visual_used = True

    return floor, emitted, float(song_bpm), final_visual_used



def emit_angle_compression(
    angle_data,
    actions,
    floor,
    freq,
    dur,
    play_bpm,
    x_mode,
    fixed_x,
    max_tiles_per_note,
    target_angle: float | None = None,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
) -> tuple[int, int, float | None, bool, bool]:
    if freq <= 0 or dur <= 0:
        return floor, 0, None, False, False

    beat_count = dur * play_bpm / 60.0
    keycount = freq * 60.0 * beat_count / max(play_bpm, EPS)

    if keycount <= EPS:
        return floor, 0, None, False, False

    x_tiles = int(math.floor(keycount + EPS))
    frac = keycount - math.floor(keycount)

    change_x = choose_change_x(keycount, x_mode, fixed_x)
    auto_angle = 180.0 * change_x / keycount

    target_used = target_angle is not None
    angle = float(target_angle) if target_used else auto_angle
    # Keep obviously invalid values from producing impossible geometry.
    if angle <= 0:
        angle = auto_angle
        target_used = False

    # Issue #3:
    # When overriding the main zip angle, the fractional last angle should
    # be corrected by the same scale ratio.
    #
    # auto_last_angle = auto_angle * frac
    # corrected_last  = auto_last_angle * (target_angle / auto_angle)
    #                 = target_angle * frac
    #
    # If disabled, the final fractional tile uses the old auto angle.
    frac_base_angle = angle

    bpm = (freq * 60.0) * (angle / 180.0)

    actions.append(set_bpm(floor, bpm))

    emitted = 0
    whole_to_emit = x_tiles
    if max_tiles_per_note > 0:
        whole_to_emit = min(whole_to_emit, max_tiles_per_note)

    for _ in range(whole_to_emit):
        add_relative(angle_data, angle)
        floor += 1
        emitted += 1

    final_visual_used = False
    if frac > 1e-6 and (max_tiles_per_note <= 0 or emitted < max_tiles_per_note):
        scaled_final_angle = frac_base_angle * frac
        prev_abs = float(angle_data[-1])
        final_angle = final_visual_angle(
            mode=final_angle_mode,
            prev_abs=prev_abs,
            scaled_final_angle=scaled_final_angle,
            custom_final_angle=final_custom_angle,
            cardinal_step=final_cardinal_step,
        )

        # Keep the note duration correct even when the final tile angle is changed
        # for visual reasons.
        #
        # desired final-tile duration = frac / freq
        # duration(angle, bpm) = (angle / 180) * (60 / bpm)
        # => bpm = freq * 60 * angle / (180 * frac)
        if final_angle <= 0:
            final_angle = scaled_final_angle

        final_bpm = (freq * 60.0) * (final_angle / max(EPS, 180.0 * frac))

        if abs(final_bpm - bpm) > 1e-6:
            actions.append(set_bpm(floor, final_bpm))
            final_visual_used = True

        add_relative(angle_data, final_angle)
        floor += 1
        emitted += 1
        bpm = final_bpm

        if abs(final_angle - scaled_final_angle) > 1e-6:
            final_visual_used = True

    return floor, emitted, bpm, target_used, final_visual_used


def flatten_curve_notes(
    notes: list[Note],
    *,
    curve_step_sec: float = 0.025,
    curve_pitch_step: float = 0.25,
) -> list[Note]:
    out: list[Note] = []
    for n in notes:
        out.extend(
            n.sample_fixed_segments(
                max_seconds=curve_step_sec,
                max_pitch_step=curve_pitch_step,
                max_segments=2000,
            )
        )
    return out


def normalize_notes_to_first(notes: list[Note]) -> tuple[list[Note], float]:
    sorted_notes = sorted((n.normalized() for n in notes if n.duration > 0), key=lambda n: (n.start, n.midi, n.end))
    if not sorted_notes:
        return [], 0.0

    first_start = sorted_notes[0].start
    normalized = [
        Note(
            max(0.0, n.start - first_start),
            max(0.0, n.end - first_start),
            n.midi,
            n.velocity,
            n.kind,
            n.midi_end,
            n.ctrl1_midi,
            n.ctrl2_midi,
            n.interpolation,
            n.target_angle,
        ).normalized()
        for n in sorted_notes
    ]
    return normalized, first_start


def parse_harmony_intervals(mode: str = "off", custom_semitone: float = 7.0) -> list[float]:
    """
    Global Harmony Charting interval list.

    The base voice is always 0 semitones. Returned values are extra voices only.
    """
    key = (mode or "off").lower().replace(" ", "_").replace("-", "_")
    if key in ("off", "none", "root_only"):
        return []
    if key in ("octave_+12", "octave", "+12", "12"):
        return [12.0]
    if key in ("fifth_+7", "perfect_fifth", "fifth", "+7", "7"):
        return [7.0]
    if key in ("major_third_+4", "major_third", "maj3", "+4", "4"):
        return [4.0]
    if key in ("minor_third_+3", "minor_third", "min3", "+3", "3"):
        return [3.0]
    if key in ("lower_octave_-12", "lower_octave__12", "lower_octave", "-12", "_12"):
        return [-12.0]
    if key in ("custom", "custom_semitone"):
        return [float(custom_semitone)]
    return []


def _note_impulse_events(
    note: Note,
    *,
    voice_index: int,
    semitone_offset: float,
    max_events: int,
    epsilon_sec: float,
) -> list[dict[str, Any]]:
    """
    Build one voice's impulse train for a note.

    Each event is a tile hit candidate. The final fractional cycle is represented
    by the last event before the note end, which matches the existing Hz export
    idea of one extra visual tile for fractional keycount.
    """
    n = note.normalized().with_pitch_offset(semitone_offset)
    if n.duration <= EPS:
        return []

    events: list[dict[str, Any]] = []
    max_events = int(max_events)
    local_t = 0.0
    emitted = 0

    if n.is_curve:
        intervals, _total_phase = curve_phase_dt_intervals(n)
        t = n.start + voice_index * epsilon_sec
        for i, dt in enumerate(intervals):
            if max_events > 0 and emitted >= max_events:
                break
            dur_pos = max(0.0, min(1.0, (t - n.start) / max(EPS, n.duration)))
            freq = max(EPS, n.freq_at(dur_pos))
            events.append({
                "time": t,
                "midi": n.midi_at(dur_pos),
                "freq": freq,
                "voice": voice_index,
                "interval": float(semitone_offset),
                "note": n,
            })
            emitted += 1
            t += max(EPS, float(dt))
        return events

    freq = max(EPS, n.freq)
    period = 1.0 / freq
    while local_t < n.duration - EPS:
        if max_events > 0 and emitted >= max_events:
            break
        t = n.start + local_t + voice_index * epsilon_sec
        events.append({
            "time": t,
            "midi": n.midi,
            "freq": freq,
            "voice": voice_index,
            "interval": float(semitone_offset),
            "note": n,
        })
        emitted += 1
        local_t += period

    return events


def build_harmony_impulse_events(
    notes: list[Note],
    *,
    harmony_mode: str = "off",
    harmony_custom_semitone: float = 7.0,
    harmony_epsilon_ms: float = 0.001,
    max_tiles: int = 200000,
    max_tiles_per_note: int = 5000,
) -> tuple[list[dict[str, Any]], int]:
    """
    Merge root + harmony impulse trains into one timeline.

    This is intended for visual Harmony Charting: it weaves multiple pitch
    cycles into one ADOFAI tile path. It is not a multi-lane audio renderer.
    """
    extra_intervals = parse_harmony_intervals(harmony_mode, harmony_custom_semitone)
    intervals = [0.0] + extra_intervals
    epsilon_sec = max(0.0, float(harmony_epsilon_ms)) / 1000.0

    events: list[dict[str, Any]] = []
    for n in notes:
        if n.duration <= EPS:
            continue
        for voice_index, interval in enumerate(intervals):
            per_voice_limit = max_tiles_per_note
            voice_events = _note_impulse_events(
                n,
                voice_index=voice_index,
                semitone_offset=interval,
                max_events=per_voice_limit,
                epsilon_sec=epsilon_sec,
            )
            events.extend(voice_events)

    events.sort(key=lambda e: (float(e["time"]), int(e["voice"]), float(e["midi"])))

    # Enforce a deterministic tiny separation. Completely simultaneous tiles are
    # technically possible at chord starts, but ADOFAI needs one serial path.
    adjusted = 0
    prev_t: float | None = None
    min_sep = max(epsilon_sec, 1e-9)
    for e in events:
        t = float(e["time"])
        if prev_t is not None and t <= prev_t + min_sep:
            t = prev_t + min_sep
            e["time"] = t
            adjusted += 1
        prev_t = t

    if max_tiles > 0 and len(events) > max_tiles:
        events = events[:max_tiles]

    return events, adjusted


def harmony_relative_angle(freq: float, play_bpm: float, *, min_angle: float = 2.0, max_angle: float = 358.0) -> float:
    """
    Use an Angle-only-like visual angle for a harmony impulse.

        angle = bpm * 180 / (freq * 60)

    This lets different harmony voices leave visibly different angle patterns.
    """
    angle = float(play_bpm) * 180.0 / max(EPS, float(freq) * 60.0)
    while angle > 360.0:
        angle *= 0.5
    return clean_relative_angle(max(min_angle, min(max_angle, angle)))


def emit_harmony_polyrhythm(
    angle_data: list[Any],
    actions: list[dict[str, Any]],
    floor: int,
    events: list[dict[str, Any]],
    *,
    play_bpm: float,
    max_tiles: int,
    current_bpm: float | None = None,
) -> tuple[int, int, float | None, int]:
    """
    Emit a single serial ADOFAI path from merged harmony impulse times.

    Each impulse becomes one tile. The time until the next impulse is preserved
    by placing a SetSpeed for that tile. The visual angle is derived from the
    source voice pitch.
    """
    if not events:
        return floor, 0, current_bpm, 0

    emitted = 0
    tiny_intervals = 0
    now = 0.0

    for i, e in enumerate(events):
        if max_tiles > 0 and emitted >= max_tiles:
            break

        t = float(e["time"])
        if i == 0 and t > now + 1e-6:
            pause_seconds(actions, floor, t - now, current_bpm)
            now = t

        if i + 1 < len(events):
            dt = max(EPS, float(events[i + 1]["time"]) - t)
        else:
            freq = max(EPS, float(e.get("freq", 1.0)))
            dt = 1.0 / freq

        if dt <= 1e-6:
            tiny_intervals += 1

        rel = harmony_relative_angle(float(e.get("freq", 1.0)), play_bpm)
        bpm = rel * 60.0 / max(EPS, 180.0 * dt)

        actions.append(set_bpm(floor, bpm))
        current_bpm = bpm
        add_relative(angle_data, rel)

        floor += 1
        emitted += 1
        now = t + dt

    return floor, emitted, current_bpm, tiny_intervals


def export_adofai(
    notes: list[Note],
    path: str | Path,
    *,
    method: str = "rabbit_zip",
    base_bpm: float = 175.0,
    angle_only_bpm: float = 1600.0,
    rabbit_x_mode: str = "floor",
    rabbit_fixed_x: float = 8.0,
    max_tiles: int = 200000,
    max_tiles_per_note: int = 5000,
    track_visual: str = "normal",
    curve_step_sec: float = 0.025,
    curve_pitch_step: float = 0.25,
    phase_continuous_glide: bool = True,
    final_angle_mode: str = "scaled",
    final_custom_angle: float = 180.0,
    final_cardinal_step: float = 90.0,
    song_filename: str | None = None,
    song_offset_ms: float | None = None,
    harmony_mode: str = "off",
    harmony_custom_semitone: float = 7.0,
    harmony_epsilon_ms: float = 0.001,
    pretty: bool = False,
) -> dict[str, int | float | str]:
    level = new_level()
    if song_filename:
        level.setdefault("settings", {})["songFilename"] = Path(str(song_filename)).name
    if song_offset_ms is not None:
        level.setdefault("settings", {})["songOffset"] = round(float(song_offset_ms), 3)
    angle_data = level["angleData"]
    actions = level["actions"]
    apply_track_visual(level, actions, track_visual)

    method_key = (method or "rabbit_zip").lower().replace(" ", "_").replace("-", "_")
    use_phase_continuous_glide = bool(phase_continuous_glide)

    if use_phase_continuous_glide:
        prepared_notes = [n.normalized() for n in notes if n.duration > 0]
    else:
        prepared_notes = flatten_curve_notes(notes, curve_step_sec=curve_step_sec, curve_pitch_step=curve_pitch_step)

    sorted_notes, first_note_offset = normalize_notes_to_first(prepared_notes)

    global_lowest_floor_x = compute_lowest_floor_x(sorted_notes)
    effective_fixed_x = global_lowest_floor_x if (rabbit_x_mode or "").lower().replace(" ", "_").replace("-", "_") in (
        "lowest_floor", "lowest", "min_floor", "minimum_floor"
    ) else rabbit_fixed_x

    floor = 1
    now = 0.0
    tiles = 0
    overlaps = 0
    used = 0
    target_angle_used = 0
    final_visual_corrections = 0
    phase_continuous_curves = 0
    current_bpm: float | None = None
    play_bpm = max(1e-6, float(angle_only_bpm if method_key in ("angle_only", "harmony", "harmony_polyrhythm") else base_bpm))

    if method_key in ("harmony", "harmony_polyrhythm"):
        level.setdefault("settings", {})["bpm"] = round(play_bpm, 6)
        current_bpm = play_bpm
        events, simultaneous_adjusted = build_harmony_impulse_events(
            sorted_notes,
            harmony_mode=harmony_mode,
            harmony_custom_semitone=harmony_custom_semitone,
            harmony_epsilon_ms=harmony_epsilon_ms,
            max_tiles=max_tiles,
            max_tiles_per_note=max_tiles_per_note,
        )
        floor, emitted, current_bpm, tiny_intervals = emit_harmony_polyrhythm(
            angle_data,
            actions,
            floor,
            events,
            play_bpm=play_bpm,
            max_tiles=max_tiles,
            current_bpm=current_bpm,
        )
        text = json.dumps(level, ensure_ascii=False, indent=2 if pretty else None, separators=None if pretty else (",", ":"))
        Path(path).write_text(text, encoding="utf-8")
        return {
            "method": method_key,
            "track_visual": track_visual,
            "phase_continuous_glide": bool(use_phase_continuous_glide),
            "input_notes_total": len(notes),
            "base_bpm": round(float(base_bpm), 6),
            "angle_only_bpm": round(float(angle_only_bpm), 6),
            "effective_play_bpm": round(float(play_bpm), 6),
            "harmony_mode": harmony_mode,
            "harmony_custom_semitone": round(float(harmony_custom_semitone), 6),
            "harmony_epsilon_ms": round(float(harmony_epsilon_ms), 6),
            "harmony_events_total": len(events),
            "simultaneous_adjusted": simultaneous_adjusted,
            "tiny_intervals": tiny_intervals,
            "first_note_offset_seconds": round(first_note_offset, 6),
            "start_floor": 1,
            "notes_total": len(sorted_notes),
            "notes_used": len(sorted_notes),
            "target_angle_ignored": sum(1 for n in sorted_notes if n.target_angle is not None),
            "target_angle_used": 0,
            "final_angle_mode": final_angle_mode,
            "final_custom_angle": round(float(final_custom_angle), 6),
            "final_cardinal_step": round(float(final_cardinal_step), 6),
            "final_visual_corrections": 0,
            "songFilename": level.get("settings", {}).get("songFilename", ""),
            "song_offset_ms": level.get("settings", {}).get("songOffset", 0),
            "overlaps_serialized": 0,
            "tiles_total": emitted,
            "floors_total": len(angle_data) - 1,
            "actions_total": len(actions),
        }

    if method_key == "angle_only":
        # One initial/global speed for the entire angle-only chart.
        # No per-note SetSpeed is needed unless final-tile visual compensation is used.
        level.setdefault("settings", {})["bpm"] = round(play_bpm, 6)
        current_bpm = play_bpm

    for n in sorted_notes:
        if max_tiles > 0 and tiles >= max_tiles:
            break

        if n.start > now + 1e-6:
            pause_seconds(actions, floor, n.start - now, current_bpm)
            now = n.start
        elif n.start < now - 1e-6:
            overlaps += 1

        audible = n.duration
        rest = 0.0

        limit = max_tiles_per_note
        if max_tiles > 0:
            remain = max_tiles - tiles
            limit = min(limit, remain) if limit > 0 else remain

        if method_key == "direct_180":
            if use_phase_continuous_glide and n.is_curve:
                floor, t, note_bpm, final_visual_used, _total_phase = emit_direct_curve_continuous(
                    angle_data,
                    actions,
                    floor,
                    n,
                    limit,
                    final_angle_mode=final_angle_mode,
                    final_custom_angle=final_custom_angle,
                    final_cardinal_step=final_cardinal_step,
                )
                phase_continuous_curves += 1
                if final_visual_used:
                    final_visual_corrections += 1
            else:
                floor, t, note_bpm = emit_direct(angle_data, actions, floor, n.freq, audible, limit)
        elif method_key == "angle_only":
            if use_phase_continuous_glide and n.is_curve:
                floor, t, note_bpm, final_visual_used, _total_phase = emit_angle_only_curve_continuous(
                    angle_data,
                    actions,
                    floor,
                    n,
                    play_bpm,
                    limit,
                    final_angle_mode=final_angle_mode,
                    final_custom_angle=final_custom_angle,
                    final_cardinal_step=final_cardinal_step,
                )
                phase_continuous_curves += 1
            else:
                floor, t, note_bpm, final_visual_used = emit_angle_only(
                    angle_data,
                    actions,
                    floor,
                    n.freq,
                    audible,
                    play_bpm,
                    limit,
                    final_angle_mode=final_angle_mode,
                    final_custom_angle=final_custom_angle,
                    final_cardinal_step=final_cardinal_step,
                )
            # In angle-only mode, target_angle is intentionally ignored because
            # the angle itself determines pitch.
            if final_visual_used:
                final_visual_corrections += 1
        else:
            if use_phase_continuous_glide and n.is_curve:
                floor, t, note_bpm, target_used, final_visual_used, _total_phase = emit_angle_compression_curve_continuous(
                    angle_data,
                    actions,
                    floor,
                    n,
                    play_bpm,
                    rabbit_x_mode,
                    effective_fixed_x,
                    limit,
                    target_angle=n.target_angle,
                    final_angle_mode=final_angle_mode,
                    final_custom_angle=final_custom_angle,
                    final_cardinal_step=final_cardinal_step,
                )
                phase_continuous_curves += 1
            else:
                floor, t, note_bpm, target_used, final_visual_used = emit_angle_compression(
                    angle_data,
                    actions,
                    floor,
                    n.freq,
                    audible,
                    play_bpm,
                    rabbit_x_mode,
                    effective_fixed_x,
                    limit,
                    target_angle=n.target_angle,
                    final_angle_mode=final_angle_mode,
                    final_custom_angle=final_custom_angle,
                    final_cardinal_step=final_cardinal_step,
                )
            if target_used:
                target_angle_used += 1
            if final_visual_used:
                final_visual_corrections += 1

        if note_bpm is not None:
            current_bpm = note_bpm

        tiles += t
        used += 1

        now = max(now, n.end)

    text = json.dumps(level, ensure_ascii=False, indent=2 if pretty else None, separators=None if pretty else (",", ":"))
    Path(path).write_text(text, encoding="utf-8")

    return {
        "method": method_key,
        "track_visual": track_visual,
        "curve_step_sec": round(float(curve_step_sec), 6),
        "curve_pitch_step": round(float(curve_pitch_step), 6),
        "phase_continuous_glide": bool(use_phase_continuous_glide),
        "phase_continuous_curves": phase_continuous_curves,
        "input_notes_total": len(notes),
        "base_bpm": round(float(base_bpm), 6),
        "angle_only_bpm": round(float(angle_only_bpm), 6),
        "effective_play_bpm": round(float(play_bpm), 6),
        "lowest_floor_x": global_lowest_floor_x,
        "effective_fixed_x": round(float(effective_fixed_x), 6),
        "first_note_offset_seconds": round(first_note_offset, 6),
        "start_floor": 1,
        "notes_total": len(sorted_notes),
        "notes_used": used,
        "target_angle_ignored": sum(1 for n in sorted_notes if method_key == "angle_only" and n.target_angle is not None),
        "target_angle_used": target_angle_used,
        "final_angle_mode": final_angle_mode,
        "final_custom_angle": round(float(final_custom_angle), 6),
        "final_cardinal_step": round(float(final_cardinal_step), 6),
        "final_visual_corrections": final_visual_corrections,
        "songFilename": level.get("settings", {}).get("songFilename", ""),
        "song_offset_ms": level.get("settings", {}).get("songOffset", 0),
        "overlaps_serialized": overlaps,
        "tiles_total": tiles,
        "floors_total": len(angle_data) - 1,
        "actions_total": len(actions),
    }
