import { useEffect, useState, type ReactNode } from "react";
import type { AppState, NoteMutationResult } from "./bridge";
import type { BlankWorkspaceOptions, HarmonicDiagramOptions, HarmonicPreview, QuickHzOptions, QuickHzResult, ToolBackendApi } from "./toolsBridge";

type Common = { api: ToolBackendApi; onClose(): void; onStatus(text: string): void };

function Modal({ title, children, onClose, wide }: { title: string; children: ReactNode; onClose(): void; wide?: boolean }) {
  return <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><section className={wide ? "modal-window wide" : "modal-window"}><header className="modal-title"><strong>{title}</strong><button onClick={onClose}>×</button></header>{children}</section></div>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="dialog-field"><span>{label}</span><div>{children}</div></label>; }
function Num({ value, min, max, step = 1, disabled, onChange }: { value: number; min: number; max: number; step?: number; disabled?: boolean; onChange(v: number): void }) { return <input type="number" value={Number.isFinite(value) ? value : 0} min={min} max={max} step={step} disabled={disabled} onChange={(e) => { const v = Number(e.target.value); if (Number.isFinite(v)) onChange(v); }} />; }

export function BlankWorkspaceDialog({ api, onClose, onStatus, onState }: Common & { onState(state: AppState): void }) {
  const [value, setValue] = useState<BlankWorkspaceOptions | null>(null);
  useEffect(() => { void api.get_blank_workspace_defaults().then(setValue); }, [api]);
  async function apply() { if (!value) return; try { const state = await api.apply_blank_workspace(value); onState(state); onStatus(state.status); onClose(); } catch (e) { onStatus(String(e)); } }
  return <Modal title="Blank workspace" onClose={onClose}><div className="dialog-body export-dialog-body">{value && <><div className="info-card">音声を外して黒い編集ワークスペースに切り替えます。既存ノートは保持されます。</div><Field label="Duration"><Num value={value.duration} min={1} max={36000} step={1} onChange={(v) => setValue({ ...value, duration: v })} /></Field><Field label="MIDI min"><Num value={value.midiMin} min={0} max={127} onChange={(v) => setValue({ ...value, midiMin: Math.round(v) })} /></Field><Field label="MIDI max"><Num value={value.midiMax} min={0} max={127} onChange={(v) => setValue({ ...value, midiMax: Math.round(v) })} /></Field></>}</div><div className="dialog-footer"><span /><button onClick={onClose}>Cancel</button><button className="primary" onClick={() => void apply()} disabled={!value}>Apply</button></div></Modal>;
}

export function QuickHzDialog({ api, onClose, onStatus }: Common) {
  const [opts, setOpts] = useState<QuickHzOptions>({ bpm: 175, hz: 16, startFloor: 0, useEndFloor: false, count: 16, endFloor: 16, addSetSpeed: true, overwrite: false });
  const [result, setResult] = useState<QuickHzResult | null>(null); const [error, setError] = useState(""); const [chart, setChart] = useState("");
  useEffect(() => { let alive = true; const id = window.setTimeout(() => void api.calculate_quick_hz(opts).then((x) => { if (alive) { setResult(x); setError(""); } }).catch((e) => { if (alive) { setResult(null); setError(String(e)); } }), 80); return () => { alive = false; window.clearTimeout(id); }; }, [api, opts]);
  async function chooseChart() { try { const x = await api.choose_quick_hz_chart(); onStatus(x.status); if (x.ok && x.path) { setChart(x.path); setOpts((o) => ({ ...o, startFloor: x.tailFloor ?? o.startFloor, endFloor: Math.max(o.endFloor, (x.tailFloor ?? 0) + Math.max(1, o.count)) })); } } catch (e) { setError(String(e)); } }
  async function append() { if (!chart) { setError("No chart selected"); return; } try { const x = await api.append_quick_hz_chart(chart, opts); onStatus(x.status); } catch (e) { setError(String(e)); } }
  async function copy() { if (result?.output) { await navigator.clipboard.writeText(result.output); onStatus("Quick Hz output copied"); } }
  async function saveText() { if (!result?.output) return; const x = await api.save_quick_hz_text(result.output); onStatus(x.status); }
  return <Modal title="Quick Hz Tools" onClose={onClose} wide><div className="dialog-body quick-hz-layout"><section className="tool-form">
    <Field label="BPM"><Num value={opts.bpm} min={0.001} max={999999} step={1} onChange={(v) => setOpts({ ...opts, bpm: v })} /></Field><Field label="Hz"><Num value={opts.hz} min={0.001} max={100000} step={1} onChange={(v) => setOpts({ ...opts, hz: v })} /></Field><Field label="Start floor"><Num value={opts.startFloor} min={0} max={10000000} onChange={(v) => setOpts({ ...opts, startFloor: Math.round(v) })} /></Field><Field label="Generate"><div className="compact-row"><label><input type="checkbox" checked={opts.useEndFloor} onChange={(e) => setOpts({ ...opts, useEndFloor: e.target.checked })} /> End floor</label>{opts.useEndFloor ? <Num value={opts.endFloor} min={0} max={10000000} onChange={(v) => setOpts({ ...opts, endFloor: Math.round(v) })} /> : <Num value={opts.count} min={1} max={10000000} onChange={(v) => setOpts({ ...opts, count: Math.round(v) })} />}</div></Field><Field label="SetSpeed"><input type="checkbox" checked={opts.addSetSpeed} onChange={(e) => setOpts({ ...opts, addSetSpeed: e.target.checked })} /></Field>
    {result && <div className="tool-results"><div>Interval <b>{result.info.intervalMs.toFixed(6)} ms</b></div><div>Beat <b>{result.info.beatMs.toFixed(6)} ms</b></div><div>Beats/hit <b>{result.info.beatsPerHit.toFixed(9)} ({result.info.beatFractionText})</b></div><div>Relative angle <b>{result.info.relativeAngle.toFixed(9)}°</b></div></div>}{error && <div className="dialog-error inline">{error}</div>}
    <div className="chart-tools"><button onClick={() => void chooseChart()}>Choose chart…</button><span title={chart}>{chart ? chart.split(/[\\/]/).pop() : "No chart"}</span><label><input type="checkbox" checked={opts.overwrite} onChange={(e) => setOpts({ ...opts, overwrite: e.target.checked })} /> Overwrite</label><button onClick={() => void append()} disabled={!chart || !result}>Append</button></div>
  </section><section className="quick-hz-output"><textarea value={result?.output ?? ""} readOnly spellCheck={false} /><div className="preview-actions"><button onClick={() => void copy()} disabled={!result}>Copy</button><button onClick={() => void saveText()} disabled={!result}>Save text…</button></div></section></div><div className="dialog-footer"><span /><button className="primary" onClick={onClose}>Close</button></div></Modal>;
}

export function HarmonicDiagramDialog({ api, selected, onClose, onStatus, onMutation }: Common & { selected: number[]; onMutation(result: NoteMutationResult, selection?: number[]): void }) {
  const [opts, setOpts] = useState<HarmonicDiagramOptions | null>(null); const [preview, setPreview] = useState<HarmonicPreview | null>(null); const [error, setError] = useState("");
  useEffect(() => { void api.get_harmonic_diagram_defaults(selected).then(setOpts); }, [api, selected]);
  useEffect(() => { if (!opts) return; let alive = true; const id = window.setTimeout(() => void api.preview_harmonic_diagram(opts).then((x) => { if (alive) { setPreview(x); setError(""); } }).catch((e) => { if (alive) { setPreview(null); setError(String(e)); } }), 100); return () => { alive = false; window.clearTimeout(id); }; }, [api, opts]);
  async function insert() { if (!opts) return; try { const result = await api.insert_harmonic_diagram(opts); onMutation(result, result.indices ?? []); onStatus(result.status); onClose(); } catch (e) { setError(String(e)); } }
  if (!opts) return <Modal title="Harmonic Diagram" onClose={onClose}><div className="dialog-loading">Loading…</div></Modal>;
  return <Modal title="Harmonic Diagram" onClose={onClose} wide><div className="dialog-body harmonic-layout"><section className="tool-form">
    <Field label="Root Hz"><Num value={opts.rootHz} min={0.001} max={100000} step={1} onChange={(v) => setOpts({ ...opts, rootHz: v })} /></Field><Field label="Root shift"><input value={opts.rootShift} onChange={(e) => setOpts({ ...opts, rootShift: e.target.value })} /></Field><Field label="Base 1D offset"><Num value={opts.base1dOffset} min={-64} max={64} onChange={(v) => setOpts({ ...opts, base1dOffset: Math.round(v) })} /></Field><Field label="Harmonics"><input value={opts.harmonics} onChange={(e) => setOpts({ ...opts, harmonics: e.target.value })} /></Field><Field label="Time unit"><select value={opts.timeUnit} onChange={(e) => setOpts({ ...opts, timeUnit: e.target.value as "seconds" | "beats" })}><option value="seconds">seconds</option><option value="beats">beats</option></select></Field><Field label="BPM"><Num value={opts.bpm} min={1} max={2000} step={1} disabled={opts.timeUnit !== "beats"} onChange={(v) => setOpts({ ...opts, bpm: v })} /></Field><Field label="Start"><Num value={opts.start} min={0} max={36000} step={.25} onChange={(v) => setOpts({ ...opts, start: v })} /></Field><Field label="Duration"><Num value={opts.duration} min={.001} max={36000} step={.25} onChange={(v) => setOpts({ ...opts, duration: v })} /></Field><Field label="EDO"><Num value={opts.edo} min={1} max={999} onChange={(v) => setOpts({ ...opts, edo: Math.round(v) })} /></Field><Field label="Offset"><Num value={opts.offset} min={-999} max={999} onChange={(v) => setOpts({ ...opts, offset: Math.round(v) })} /></Field>{error && <div className="dialog-error inline">{error}</div>}
  </section><section className="harmonic-preview">{preview && <><div className="preview-summary">{preview.startSeconds.toFixed(6)}s – {preview.endSeconds.toFixed(6)}s</div>{preview.rows.map((r, i) => <div className="harmonic-row" key={i}><b>#{r.pitchNumber}</b><span>{r.local}</span><span>{r.ratio}</span><span>{r.hz.toFixed(6)} Hz</span><span>MIDI {r.midi.toFixed(6)}</span></div>)}</>}</section></div><div className="dialog-footer"><span /><button onClick={onClose}>Cancel</button><button className="primary" onClick={() => void insert()} disabled={!preview}>Insert</button></div></Modal>;
}

export function LanguageDialog({ api, onClose, onStatus }: Common) {
  const [current, setCurrent] = useState(""); const [langs, setLangs] = useState<string[]>([]);
  useEffect(() => { void api.get_language_state().then((x) => { setCurrent(x.current); setLangs(x.available); }); }, [api]);
  async function apply() { const x = await api.set_app_language(current); onStatus(x.status); onClose(); }
  return <Modal title="Language" onClose={onClose}><div className="dialog-body export-dialog-body"><Field label="Language"><select value={current} onChange={(e) => setCurrent(e.target.value)}>{langs.map((x) => <option key={x} value={x}>{x === "ja" ? "日本語" : x === "en" ? "English" : x}</option>)}</select></Field><div className="info-card">変更は保存され、UI全体への反映は再起動後です。</div></div><div className="dialog-footer"><span /><button onClick={onClose}>Cancel</button><button className="primary" onClick={() => void apply()} disabled={!current}>Apply</button></div></Modal>;
}

export function UpdateDialog({ api, onClose, onStatus }: Common) {
  const [info, setInfo] = useState<{ version: string; text: string; info: string } | null>(null);
  useEffect(() => { void api.get_update_info().then(setInfo); }, [api]);
  async function open() { const x = await api.open_releases_page(); onStatus(x.ok ? "Opened releases" : `Releases: ${x.url}`); onClose(); }
  return <Modal title="Check for updates" onClose={onClose}><div className="dialog-body export-dialog-body">{info ? <><div className="info-card">{info.text}</div><div className="info-card">{info.info}</div></> : <div className="dialog-loading">Loading…</div>}</div><div className="dialog-footer"><span /><button onClick={onClose}>Later</button><button className="primary" onClick={() => void open()}>Open Releases</button></div></Modal>;
}
